### PR TITLE
Initial SearXNG Support

### PR DESCRIPTION
**Pull request by rad4day**
We all love Qwant but SearXNG is so much more versatile.
This PR intends to provide searx as a replacement for Qwant.

There has been some initial testing and it seems to work. Current problems:

- [ ] URL is not configurable
- [ ] favicon isn't working as it is an svg file(?)
- [x] Doesn't state where it got its result from i.e. google, wikidata, duckduckgo
- [x] Infobox content is ignored. Maybe this isnt even an issue.
- [x] External Bangs (e.g. !!aw dbus) break everything :)

Have fun. You've got a pretty wild code-base.

### CODE REVIEW

**Comment by MartinWitt** [comment]
Are there any plans to ever merge this feature? I kinda need this.

**Comment by MartinWitt** [comment]
Any progress on this?

**Comment by MartinWitt** [comment]
@SirYwell do you have time to have a look and finish this PR?

**Review by SirYwell — APPROVED** [review]
LGTM

**Comment by MartinWitt** [comment]
https://user-images.githubusercontent.com/25300639/204107598-d783e066-c44d-4cb0-84d0-c741a705c202.mp4

**Comment by MartinWitt** [comment]
Any updates?

**Comment by MartinWitt** [comment]
Any progress?

**Pull request closed without merging**
